import type { Metadata } from "next";
import { Playfair_Display, Work_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import { BookProvider } from "@/context/BookContext";
import { ToastContainer } from "react-toastify";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

const plafairDisplay = Playfair_Display({
  variable: "--font-plafair",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${workSans.variable} ${plafairDisplay.variable} h-full antialiased`}
    >
      <body>
        <BookProvider>
          <Navbar />
          <main className="container mx-auto">
            {children}
          </main>
          <Footer />
        </BookProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
